### PR TITLE
Slovenian translation error fix

### PR DESCRIPTION
**Pull request by primozs**
- change in line 176 %(welt2000)s is causing an error
- uncomment other translations

### CODE REVIEW

**Comment by primozs** [comment]
There are two additional issues with Slovenian translation.
1. the flag is wrong (SieraLeone). Slovenian country code is "SI" and language code is "sl"
https://en.wikipedia.org/wiki/Slovene_language
https://groups.google.com/forum/#!topic/django-developers/AV-Li9Q4Atc
but it seams flags css thinks it should be "si". How should we solve this?

2. š character does not work, it prints "8" instead. This is font issue and is also the problem with at least Czech language. It seams ubuntu does not have this character supported.

**Comment by primozs** [comment]
For the travis i don't know what is the problem because assets build is passing normally on my side.

**Comment by TobiasLohner** [comment]
We use ISO_3166-2 country codes for the flags, but ISO 639-1 language codes for the languages. There's a conversion table in lib/helpers/country.py - i'll added slovenian to that one and merge your changes. Thanks!

**Comment by TobiasLohner** [comment]
Btw, the travis build failed due to https://github.com/gevent/gevent/issues/513 - the same on the live server. We have to wait for the gevent 1.0.2 release to get this fixed.

**Comment by primozs** [comment]
@TobiasLohner Hello, great! Also i have just updated the Slovenian .po file and revisited translations. I would like to merge this also.

**Pull request merged**
