### PR TITLE
Spelling changes

### PR DESCRIPTION
**Pull request by clementallen**
I noticed that in some places on the website it was referring to `email` and in others it was referring to `eMail`.

I've gone through the translations and anywhere else this occurred and made everything consistent which should prevent things like this:
skylinesemail

### CODE REVIEW

**Comment by Turbo87** [comment]
I personally would prefer "eMail", but then again you're the native speaker. There however instances where the term is used in titles and I think "email Address" with "Address" written capitalized looks a bit strange.

@TobiasLohner any comments?

**Comment by clementallen** [comment]
I very rarely see it displayed as "eMail" so it caught my attention when I noticed it.  I think that "email" fits in a lot better with the rest of the site and most of the internet itself.  I'm happy to go through and correct all capitalization of the sentences to fit in better with the change if you wish?

**Comment by TobiasLohner** [comment]
According to collins dictionary (which can be accessed for free online), it's either "email" or "e-mail". In german, the spelling is "Email" or "E-Mail" (ref. Duden).

**Comment by Turbo87** [comment]
maybe I'm too affected by the "iPhone" ;)

@clementallen I guess "Email Address" would be better indeed. Otherwise: nice work! :+1:

**Comment by clementallen** [comment]
@Turbo87 haha it is all too easy in this day and age to start spelling works in the style of Apple :P
Sounds good, I'll go through and modify the translations.

**Comment by clementallen** [comment]
@Turbo87 and @TobiasLohner I've made the necessary changes and have created <a href="https://github.com/skylines-project/skylines/pull/380">this pull request</a>.

This one is no longer necessary and will be closed.

**Comment by Turbo87** [comment]
@clementallen just FYI: you could've also reused this pull request. you just have to amend the commits and force-push to the same branch.

**Pull request closed without merging**
