### PR TITLE
Add aircraft model in json datas

### PR DESCRIPTION
**Pull request by pyrog**
Needed by ember/app/components/plane-icons-composer.js to display the appropriate symbol.

See #545, #546

### CODE REVIEW

**Comment by Turbo87** [comment]
Did you test this? I'm not sure this will work since `flight.model` is itself a relationship

**Comment by pyrog** [comment]
> Did you test this?

No, because I don't have a test server 😉 

Also, I don't have any experience with [flask-sqlalchemy](http://flask-sqlalchemy.pocoo.org/2.1/queries/).

So, could you help me to export all the model's fields in json ?
Or at least kind/type ?

Should I write this ?

```python
model=flight.model.kind
```

Or add somewhere?

```python
        .outerjoin(Flight.model) \
        .options(contains_eager(Flight.model)) \
```

Thank you

**Comment by Turbo87** [comment]
@pyrog I just tried this locally and `model` always returns `null` for me

**Comment by pyrog** [comment]
Between our last messages, I installed the server locally under Vagrant and it works fine.
I should check if we have both the same version of DB and dependencies.

**Pull request closed without merging**
