### PR TITLE
Update airspace_list.txt to fix link to us airspace

### PR DESCRIPTION
**Pull request by henryxa**
updated reference line 26 to fix us airspace file to current soaring web location

### CODE REVIEW

**Review by Turbo87 — APPROVED** [review]
thanks 👍

**Comment by henryxa** [comment]
Hi Turbo. Can you tell me what's the process from here to actually get to this is on the actual skylines web page. I have to say that this was straight forward so far for someone that has no clue as to what the process is. I just don't know what triggers the change being on the actual web or when that would happen. I realize this sounds like I can't wait (which is true) but also, it's a bit difficult to just go blind and wait. Thank you for reviewing my change

**Comment by Turbo87** [comment]
Hi @henryxa, sorry for the late reply. This is a process that needs to be manually triggered, is quite slow, and unfortunately has often failed in the past so I rarely do it 😞

**Comment by henryxa** [comment]
Thanks for the reply... Hope you do it successfully soon... Skylines is a really great tool to looks at flights performed and it's always good to see the airspace.. cheers!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request merged**
