### PR TITLE
Add information about Docker setup.

### LINKED ISSUE #2311: [Question] Add container config for VSCode
Hey @Turbo87,

VSCode make it super easy [to develop code in a Docker env](https://docs.microsoft.com/en-us/learn/modules/use-docker-container-dev-env-vs-code/2-use-as-development-environment).

Basically you can connect to a container and work as it you were working on your local env.

If you think it is valuable, I could submit a PR to:
- remove the vagrant files,
- add the VSCode config files,
- add some doc on how to use VSCode for dev.

This is the environment I use for dev and it's quite easy and powerful.

If there is a dummy proof (I'm the dummy here) env for development it could only ease the contributions.

Let me know what you think.

### PR DESCRIPTION
**Pull request by vicb**
Delete the outdated Vagrant config.

fixes #2311

### CODE REVIEW

**Comment by Turbo87** [comment]
this generally LGTM, but AFAICT there are still a few things missing before we can switch over. primarily, the docker-compose file currently only sets up the database that is used for testing, but not the one that is used by the server when running in development.

I don't know exactly yet how to fix it. The first idea that I had was making the database name configurable with an env var, but it would have to be done in a way that does conflict with how we currently set it on the production server (which does not use Docker... yet).

**Comment by vicb** [comment]
> there are still a few things missing before we can switch over

The thing is the Vagrant image doesn't work anymore because `ppa:jonathonf/python-2.7` is no more available. See details [here](https://stackoverflow.com/questions/59501998/failed-to-fetch-packages-from-jonathonf-repository-while-running-dockerfile-from/59504515#59504515).

So I think this PR is still valuable over the current state.

Maybe the way forward is to create a docker-compose that sets up an env that is suitable for prod and build on top of that of the dev environment ? The simplest way would be to add a second Postgres container for the test DB ?

**Comment by Turbo87** [comment]
> Maybe the way forward is to create a docker-compose that sets up an env that is suitable for prod and build on top of that of the dev environment ?

I've been wondering about that, but since both environment have slightly different requirements I'm not sure how realistic that will be. It might make sense to have one file for dev/testing and a dedicated file for production.

> The simplest way would be to add a second Postgres container for the test DB ?

I think it should be possible to have second database inside the existing container, we just have to figure out how exactly :D

**Comment by vicb** [comment]
@Turbo87 nice PR (#2316) !

I don't this it closes this one though ?

**Comment by Turbo87** [comment]
oh, shit, that was unintentional. I didn't think that mentioning the comment would close the whole PR 😱

**Comment by vicb** [comment]
> oh, shit, that was unintentional. I didn't think that mentioning the comment would close the whole PR 😱

No problem. I guess it's the combination of "resolve" + issue/PR number (also "works" with "fix(es)" and "close(s)").

**Pull request merged**
