### PR TITLE
Direct upload API

### PR DESCRIPTION
**Pull request by TobiasLohner**
Can be tested with curl:

curl --header "X-SkyLines-Tracking-Key: 1234" --header "X-SkyLines-Filename: file.igc" --header "Content-Type: application/octet-stream" --data-binary @file.igc http://servername/upload

### CODE REVIEW

**Comment by Turbo87** [comment]
to be honest I don't like it that much due to several reasons:

- it seems that the API does not return JSON but `text/plain` instead
- Authentication via custom `X-SkyLines-Tracking-Key` header instead of `Authorization: bearer <token>`
- it's still mixing up flights and and IGC files, while in reality an IGC file can contain multiple flights and one flight could be recorded in multiple loggers resulting in multiple IGC files (XCSoar and Flarm for example)

I've written down a rough sketch of my plan for the Skylines API at https://gist.github.com/Turbo87/72d73a548dbf953e1f5e. It roughly follows typical REST patterns and some parts are similar to the well documented GitHub API.

**Comment by TobiasLohner** [comment]
>   * it seems that the API does not return JSON but |text/plain| instead

You are free to implement a JSON reader api for xcsoar. We can change to
JSON then.

>   * Authentication via custom |X-SkyLines-Tracking-Key| header instead
>     of |Authorization: bearer <token>|

That's a point, a "Authorization"-header has some benefits when it comes
to caching proxies.

>   * it's still mixing up flights and and IGC files, while in reality an
>     IGC file can contain multiple flights and one flight could be
>     recorded in multiple loggers resulting in multiple IGC files (XCSoar
>     and Flarm for example)

This has nothing to do with this api.


> 
> I've written down a rough sketch of my plan for the Skylines API at
> https://gist.github.com/Turbo87/72d73a548dbf953e1f5e. It roughly follows
> typical REST patterns and some parts are similar to the well documented
> GitHub API.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skylines-project/skylines/pull/400#issuecomment-102007159>.
> 

-- 
Lüsternheit: Spiel mit dem zu Genießenden. Spiel mit dem
Genossenen.
		-- Goethe, Maximen und Reflektionen, Nr. 619

**Comment by Turbo87** [comment]
> You are free to implement a JSON reader api for xcsoar. We can change to JSON then.

My approach is that our API is JSON by default, and only if requested otherwise it should return something else. If this handler is specific to XCSoar then why not make it `api.skylines.aero/xcsoar/upload` instead?

**Comment by Turbo87** [comment]
is there a reason for using a header for the filename property? can't we just use `?filename=blabla.igc` instead?

**Comment by TobiasLohner** [comment]
> If this handler is specific
> to XCSoar then why not make it |api.skylines.aero/xcsoar/upload| instead?

I'm fine with that, but I would make it /upload/xcsoar or even
/upload/?api=xcsoar (or "plain") instead.


-- 
Wer den Neid nicht ertragen kann, muß auch den Ruhm nicht wollen.
		-- Ernst Raupach

**Comment by TobiasLohner** [comment]
> is there a reason for using a header for the filename property? can't we
> just use |?filename=blabla.igc| instead?

This looks more like a request for filename 'blabla.igc' in my eyes, I
prefer the header field.


-- 
Ein gewöhnlicher Verstand ist wie ein schlechter Jagdhund, der die
Fährte eines Gedankens schnell annimmt und schnell wieder verliert.
		-- Hugo von Hoffmannsthal

**Comment by mongrelion** [comment]
@TobiasLohner @Turbo87 it's not clear what the way forward is for this PR. It's also been 5 years since it was opened.
Would you consider closing it?

**Comment by Turbo87** [comment]
given all of the conflicts, I agree that closing (and possibly recreating it) is probably the best way forward.

**Pull request closed without merging**
