### PR TITLE
Use Backbone.js

### PR DESCRIPTION
**Pull request by TobiasLohner**
Work in progress, more to come.
This might become handy at some point...

### CODE REVIEW

**Comment by Turbo87** [comment]
I've experimented with backbone in the past and while I've originally
planned to use it for skylines I'm not so sure about it anymore. I've done
a lot of work with emberjs lately and I think in the long term it will be
the better choice.

Backbone is just one little puzzle piece and you usually need many more
which you need to find and hope that they fit together. For ember most of
the pieces are developed in sync of each other and work really well
together.

TobiasLohner <notifications@github.com> schrieb am Do., 24. Dez. 2015 18:58:

**Comment by lordfolken** [comment]
I would also go the emberjs route. Its a clear frontend/backend seperation. We should aim for this, as we need to be able to scale the service.

**Comment by TobiasLohner** [comment]
Thanks for your feedback. I like the simplicity and good documentation of backbone.js, but I fully agree that it requires some additional pieces to be fully functional (two-way data binding, ...). I've had a closer look on AngularJS but not on emberjs. AngularJS was way to complex and "integrated" for my taste, therefore the choice of backbone. I'll try ember, too. Let's see how it works.

**Comment by Turbo87** [comment]
Funny thing is that angular and ember are actually moving away from two way
data binding. Instead they use one way data bindings with explicit actions
and two way only when explicitly specified.

Ember is quite "integrated" too if used in the default way with ember-cli,
but it can be used in a modular way too which should help with the
transition. What I particularly like about ember is their data store
implementation though which we would probably only use in a later step.

TobiasLohner <notifications@github.com> schrieb am Di., 12. Jan. 2016 08:41:

**Comment by TobiasLohner** [comment]
I played around with ember a bit but I really don't like it. Its quite heavy (adding another ~100 kb gzipped js code) and for my taste it's too hard for a piece by piece transition of our legacy code to the 'emberish' way. Btw in my eyes we don't need all that server-side fancy stuff which seems to make ember quite a bit unique.

**Comment by Turbo87** [comment]
FWIW https://github.com/Turbo87/skylines-ember

**Comment by TobiasLohner** [comment]
Are you serious about implementing skylines in ember?!?

**Comment by Turbo87** [comment]
yes

**Comment by TobiasLohner** [comment]
That's sad.

**Comment by TobiasLohner** [comment]
What's the benefit of using node.js instead of python? Does it pay off?

**Comment by Turbo87** [comment]
my plan is to move away from the server-rendering and have the python code only provide the API service in the end. IMHO this should simplify our codebase quite a bit and makes it more testable (as you can already notice in some of the API handlers that I touched in the last days).

for the user it certainly has the disadvantage of having to download a large chunk of javascript upfront, but once that is downloaded and properly cached the data downloads should be faster. since we can cache the data on the client we don't have to reload the flight paths all the time for example.

I'm aware that mixing Ember with ol3 is not particularly easy, but I still think it's possible and worth investigating.

**Comment by Turbo87** [comment]
> What's the benefit of using node.js instead of python? Does it pay off?

I don't want to use Ember's server-side rendering yet, because that's still considered experimental. The API service should always remain in Python and won't be ported to node.js. IMHO porting that to another language has no big advantages at the moment.

**Comment by Turbo87** [comment]
> Are you serious about implementing skylines in ember?!?

I should clarify that my "yes" response was only targetting the web frontend, not the server-side code! Sorry if that caused any confusion.

**Comment by TobiasLohner** [comment]
Hm, as far as i've seen the newer js frameworks are moving back to server-side rendering. It's alot more browser-friendly and enables non-js clients (and slow clients) to read the page (search engines, ...).

And I'm concerned about the integration of ol3, cesium, all the bootstrap and flot stuff into ember. And of course we add another 100 kb of boilerplate (mobile connections are still very slow nowadays).

**Comment by TobiasLohner** [comment]
We already have a very versatile frontend, so we should focus on implementing new features instead of changing the frontend code.

**Comment by Turbo87** [comment]
> Hm, as far as i've seen the newer js frameworks are moving back to server-side rendering. It's alot more browser-friendly and enables non-js clients (and slow clients) to read the page (search engines, ...).

that's true and that's why the ember-fastboot project was started to investigate in rendering ember apps on the server-side. it basically combines the advantages of server-side rendering (fast HTML response, SEO, ...) with the advantages of client-side frameworks (virtual DOM rendering, no redundant HTML downloads, ...)

> And I'm concerned about the integration of ol3, cesium, all the bootstrap and flot stuff into ember. 

integrating bootstrap is actually fairly easy. ol3 and cesium might be a challenge, but I'm sure it can be done. if I'm wrong I consider my experiment failed, but having the API service is still useful for other things as well.

> And of course we add another 100 kb of boilerplate (mobile connections are still very slow nowadays).

that is true, but then again you don't have to download the redundant HTML stuff all the time and you can cache flight paths for example. the disadvantage is of course that you will need to download the large JS chunk on first visit until ember-fastboot is used.

> We already have a very versatile frontend, so we should focus on implementing new features instead of changing the frontend code.

that is actually my problem. IMHO our frontend code is too tightly coupled to the backend code and rendering most of it on the server means we simply can't implement some things that I would like to have. or at least it would be rather difficult and at the end we would have implemented something like ember as well.

one example is the whole tracking UI which I would like to be much more dynamic. that however means that we need to do a lot more client-side rendering from what I've experienced so far that is much easier in Ember than in e.g. Backbone.

**Comment by TobiasLohner** [comment]
> one example is the whole tracking UI which I would like to be much more dynamic. that however means that we need to do a lot more client-side rendering from what I've experienced so far that is much easier in Ember than in e.g. Backbone.

I don't get the point. I agree the tracking UI needs some work, actually I'd like to get rid of it and have a single scoring list only. But with my recent changes (using backbone) we only have to change the way how tracking flights are handled on the backend. The frontend part is almost identical already.

Otoh I dislike the idea of having more javascript / node.js code. It's not really object oriented, nearly everything as to be done async (which adds many pitfalls), and the coding style of javascript isn't that readable and maintainable as python code. There may be some performance benefits on the backend, but I doubt our application will every grow so large we would need those. The current bottleneck are the number of round-trips needed to load the pages (and still it's not a problem atm).

**Comment by TobiasLohner** [comment]
I've thought about your ideas a bit and I'd like to continue with backbone for now. We'll be able to introduce the task planning shortly and the tracking ui can be extended with backbone, too.

My other short-term goals are more about the API, adding support for wave and thermal exchange protocols for the bidirectional live tracking and of course the still open direct upload from xcsoar. Those won't collide with your ideas.

**Comment by Turbo87** [comment]
> I've thought about your ideas a bit and I'd like to continue with backbone for now.

feel free to continue with the backbone stuff, but sooner or later I'm planning to switch to Ember if it works as planned.

**Comment by Turbo87** [comment]
Closing this as we've transitioned to Ember.js by now

**Pull request closed without merging**
