### PR TITLE
Flight page (continuation of #337)

### PR DESCRIPTION
**Pull request by TobiasLohner**
"Detailed statistics" and some minor adjustments still missing.
skylines-flight-page

### CODE REVIEW

**Comment by Turbo87** [comment]
@TobiasLohner btw my plan was to put the path details table above the baro into the sidebar too and make the baro collapseable

**Comment by kilozwo** [comment]
Maybe it is a good idea to make the statistic boxes minimizeable?

**Comment by TobiasLohner** [comment]
@kilozwo: the sidebar? click on the selected icon.

**Comment by kilozwo** [comment]
@TobiasLohner: Yes, that's what I was thinking about. Thanks...

**Comment by primozs** [comment]
It looks really nice!

**Comment by Turbo87** [comment]
@kilozwo there should probably be a close/minimize button somewhere to make it more intuitive. thanks for the feedback!

**Comment by Turbo87** [comment]
@TobiasLohner the fullscreen button doesn't seem to have any effect on Chrome+Android

**Comment by BrunoDijols** [comment]
Please, do not forget us who look at the map on a 4" smartphone to look at where our flying friends have to be picked up while we are driving. So, if it could be kept easy to see quickly who is where, that would keep our life easy. Thanks. BrunoD

**Comment by Turbo87** [comment]
@BrunoDijols we won't forget that. do you think it is harder than before? and if so, why?

**Comment by BrunoDijols** [comment]
I forgot to say the pilots' list hiding the  map only happened about
beginning of march 2015.
BrunoD

**Pull request merged**
