### PR TITLE
Javascript cleanup

### PR DESCRIPTION
**Pull request by TobiasLohner**
Reduce dependencies within the code.

### CODE REVIEW

**Comment by TobiasLohner** [comment]
@Turbo87: any objections?

**Comment by Turbo87** [comment]
I'm fine with removing IE8 support. any other major changes?

**Comment by TobiasLohner** [comment]
No other major changes, only code reorganisation to remove any global variables. Some parts can be compiled with closure compiler in advanced mode now, some don't (yet).

It's mostly preparing to add prosoar finally...

**Comment by Turbo87** [comment]
I wish we could just use http://webpack.github.io/ and use proper CommonJS modules instead of all these implicit dependencies...

**Pull request merged**
